var searchData=
[
  ['whitelabelgetsignupfields_0',['WhiteLabelGetSignUpFields',['../group__WhiteLabel.html#gac3bebff3d84fcf00e83a636e20250e35',1,'LootLocker::Requests::LootLockerSDKManager']]],
  ['whitelabellogin_1',['whitelabellogin',['../group__WhiteLabel.html#ga0bbd98a998fbff3e4ec3b40068e7f8cc',1,'LootLocker.Requests.LootLockerSDKManager.WhiteLabelLogin(string email, string password, Action&lt; LootLockerWhiteLabelLoginResponse &gt; onComplete)'],['../group__WhiteLabel.html#ga383e4079b0dae53f7a3bf8beafedfad1',1,'LootLocker.Requests.LootLockerSDKManager.WhiteLabelLogin(string email, string password, bool remember, Action&lt; LootLockerWhiteLabelLoginResponse &gt; onComplete)']]],
  ['whitelabelloginandstartsession_2',['WhiteLabelLoginAndStartSession',['../group__WhiteLabel.html#ga4f12b199b7d439ea198baa8976380f86',1,'LootLocker::Requests::LootLockerSDKManager']]],
  ['whitelabelrequestpassword_3',['WhiteLabelRequestPassword',['../group__WhiteLabel.html#ga1fa81cc7c0e01aacf410651f65ed1118',1,'LootLocker::Requests::LootLockerSDKManager']]],
  ['whitelabelrequestverification_4',['whitelabelrequestverification',['../group__WhiteLabel.html#gab522e3774670ed5e2c144868c7945773',1,'LootLocker.Requests.LootLockerSDKManager.WhiteLabelRequestVerification(int userID, Action&lt; LootLockerResponse &gt; onComplete)'],['../group__WhiteLabel.html#ga88d99470ebd41687d662d91ca5f94ec5',1,'LootLocker.Requests.LootLockerSDKManager.WhiteLabelRequestVerification(string email, Action&lt; LootLockerResponse &gt; onComplete)']]],
  ['whitelabelsignup_5',['whitelabelsignup',['../group__WhiteLabel.html#gac9e156a4f6037ac98e6af8d192c7d17d',1,'LootLocker.Requests.LootLockerSDKManager.WhiteLabelSignUp(string email, string password, Action&lt; LootLockerWhiteLabelSignupResponse &gt; onComplete)'],['../group__WhiteLabel.html#gae4abce02f72684e022c463e893087af5',1,'LootLocker.Requests.LootLockerSDKManager.WhiteLabelSignUp(string email, string password, LootLockerWhiteLabelCustomFieldValue[] customFields, Action&lt; LootLockerWhiteLabelSignupResponse &gt; onComplete)']]]
];
