name: Generate changelog from release
run-name: generate-changelog
on:
  release:
      types: [published]
  workflow_dispatch: {}

jobs:
  generate-changelog:
    name: Generate changelog from release
    runs-on: [ubuntu-latest]
    steps:
      - name: Install jq
        run: |
          sudo apt install jq
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          path: ./sdk
      - name: Generate changelog from latest release
        run: |
          ./sdk/.github/scripts/generate-changelog.sh unity-sdk "Unity SDK" "${{ SECRETS.OPEN_AI_API_KEY }}"
      - name: Cat changelog so you can get it without downloading
        run: cat ./*.md
      - name: Expose changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: ./*.md
