name: Local Backend Test
on:
  push:
    branches: # Made towards the following
      - ci/*

jobs:
  run-local-backend:
    name: Set up local backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout devenv repository
        uses: actions/checkout@v4
        with:
          repository: lootlocker/devenv
          path: devenv
          ref: bailando/ci-tester
          token: ${{ SECRETS.LL_CI_BACKEND_REPO_ACCESS_TOKEN }}
      - name: Checkout php-backend repository
        uses: actions/checkout@v4
        with:
          repository: lootlocker/php-backend
          path: php-backend
          token: ${{ SECRETS.LL_CI_BACKEND_REPO_ACCESS_TOKEN }}
      - name: Checkout gitops-lootlocker repository
        uses: actions/checkout@v4
        with:
          repository: lootlocker/gitops-lootlocker
          path: gitops-lootlocker
          token: ${{ SECRETS.LL_CI_BACKEND_REPO_ACCESS_TOKEN }}
      - name: Checkout go-backend repository
        uses: actions/checkout@v4
        with:
          repository: lootlocker/go-backend
          path: go-backend
          token: ${{ SECRETS.LL_CI_BACKEND_REPO_ACCESS_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Run Mage
        uses: magefile/mage-action@v3
        with:
          install-only: true
      - name: Check Go version
        run: |
          go version
      - name: Check Mage version
        run: |
          mage --version
      - name: Check docker & docker compose versions
        run: |
          docker -v
          docker compose version
      - name: Launch devenv
        run: |
          cd devenv
          mage env:setupsilent dev false false
          mage env:upsilent dev
          mage deps:installsilent dev
      - name: Check that devenv is up
        run: |
          docker inspect dev-php-backend
      - name: Setup Go to use access token for private repos
        env:
          GH_ACCESS_TOKEN: ${{ SECRETS.LL_CI_BACKEND_REPO_ACCESS_TOKEN }}
        run: |
          git config --global url."https://${GH_ACCESS_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          export GOPRIVATE=github.com/lootlocker/*
          export GONOPROXY=localhost
          export GITHUB_ACCESS_TOKEN=${{ SECRETS.LL_CI_BACKEND_REPO_ACCESS_TOKEN }}
      - name: Configure Go backend
        run: |
          cd go-backend
          echo ${{ SECRETS.GO_BACKEND_CONF_FILE }} | base64 --decode > infrastructure/dev.local.env
          go run . jobs migrate
      - name: Run Go Backend
        run: |
          mkdir logs
          cd go-backend
          go run . > ../logs/go-backend.log 2>&1 &
          curl -X HEAD http://localhost:9999/__/ready --retry 30 --retry-delay 1 --retry-all-errors --fail
      - name: Cat Go Backend logs
        if: always()
        run: |
          cat logs/go-backend.log
      #- name: Run Go backend
      #  uses: JarvusInnovations/background-action@v1
      #  with:
      #    run: |
      #      go run .
      #    working-directory: go-backend
      #    wait-for: 2m
      #    tail: true
      #    log-output: stderr,stdout
      #    log-output-resume: stderr
      #    log-output-if: failure
      #    wait-on: |
      #      tcp:localhost:8080
      - name: Ping local backend
        run: |
          curl --location --request POST "http://localhost:8080/admin/v1/signup" --header "Content-Type: application/json" --data-raw "{ \"organisation\": \"Some Organisation\", \"name\": \"Some One\", \"email\": \"dev@lootlocker.com\", \"password\": \"password\"}"
          