name: Local Backend Test
on:
  push:
    branches: # Made towards the following
      - ci/*

jobs:
  run-local-backend:
    name: Set up local backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout devenv repository
        uses: actions/checkout@v4
        with:
          repository: lootlocker/devenv
          path: devenv
          token: ${{ SECRETS.LL_CI_BACKEND_REPO_ACCESS_TOKEN }}
      - name: Checkout php-backend repository
        uses: actions/checkout@v4
        with:
          repository: lootlocker/php-backend
          path: php-backend
          token: ${{ SECRETS.LL_CI_BACKEND_REPO_ACCESS_TOKEN }}
      - name: Checkout gitops-lootlocker repository
        uses: actions/checkout@v4
        with:
          repository: lootlocker/gitops-lootlocker
          path: gitops-lootlocker
          token: ${{ SECRETS.LL_CI_BACKEND_REPO_ACCESS_TOKEN }}
      - name: Checkout go-backend repository
        uses: actions/checkout@v4
        with:
          repository: lootlocker/go-backend
          path: go-backend
          token: ${{ SECRETS.LL_CI_BACKEND_REPO_ACCESS_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Run Mage
        uses: magefile/mage-action@v3
        with:
          install-only: true
      - name: Check Go version
        run: |
          go version
      - name: Check Mage version
        run: |
          mage --version
      - name: Check docker & docker compose versions
        run: |
          docker -v
          docker compose version
#      - name: Ping local backend
#        run: |
#          curl --location --request POST "http://localhost:8080/admin/v1/signup" --header "Content-Type: application/json" --data-raw "{ \"organisation\": \"Some Organisation\", \"name\": \"Some One\", \"email\": \"dev@lootlocker.com\", \"password\": \"password\"}"
          