name: Selfhosted Runner Proof of Concept
run-name: selfhosted-poc
on:
  workflow_dispatch: {}

jobs:
  ping-stage-test:
    name: Ping stage backend
    runs-on: [ubuntu-latest]
    steps:
      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ SECRETS.CI_TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ SECRETS.CI_TS_OAUTH_SECRET }}
          tags: tag:ci        
      - name: Ping stage
        run: |
          curl -X POST "${{ SECRETS.LL_STAGE_URL }}/game/v2/session/guest" -H "Content-Type: application/json" -d "{\"game_key\": \"dev_dc52acb52a8b49be81761e709f1df9fd\", \"game_version\": \"0.10.0.0\", \"player_identifier\": \"k8s-runner-guest\"}"
