name: Using local backend in other workflow
on:
  push:
    branches: # Made towards the following
      - ci/*

jobs:
  run-test:
    name: Test local backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          path: sdk
      - name: ls
        run: |
            mv ./sdk/.github/workflows/local-backend-test.yml ./sdk/.github/workflows/action.yml
            ls -als sdk/.github/workflows/
      - name: Run local backend
        uses: ./sdk/.github/workflows/
      - name: Signup to backend
        run: |
          curl --location --request POST "http://localhost:8080/admin/v1/signup" --header "Content-Type: application/json" --data-raw "{ \"organisation\": \"Some Organisation\", \"name\": \"Some One\", \"email\": \"dev@lootlocker.com\", \"password\": \"password\"}"